---
- name: Shelly Gen1 - Timeserver setzen
  hosts: shelly_gen1
  gather_facts: false
  vars:
    ntp_server: "pool.ntp.org"
  tasks:
    - name: Timeserver konfigurieren
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}/settings?sntp_server={{ ntp_server }}"
        url_username: "{{ ansible_user }}"
        url_password: "{{ ansible_password }}"
        method: GET
        force_basic_auth: yes
        timeout: 10
      register: result

    - name: Ergebnis anzeigen
      debug:
        var: result.json
