---
- name: Shelly Gen2/3 - Timeserver setzen
  hosts: shelly_gen2
  gather_facts: false
  vars:
    ntp_server: "192.168.178.4"
  tasks:
    - name: Variablen anzeigen
      debug:
        msg: "Host: {{ ansible_host }} User: {{ ansible_user }}"

    - name: Timeserver konfigurieren
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}/rpc"
        url_username: "{{ ansible_user }}"
        url_password: "{{ ansible_password }}"
        method: POST
        force_basic_auth: no
        http_agent: "ansible"
        body_format: json
        body:
          id: 1
          method: "Sys.SetConfig"
          params:
            config:
              sntp:
                server: "{{ ntp_server }}"
        timeout: 10
      register: result

    - name: Ergebnis anzeigen
      debug:
        msg: "Ergebnis: {{ result.json }}"
