---
- name: Shelly Gen2/3 - Timeserver setzen
  hosts: shelly_gen2
  gather_facts: false
  vars:
    ntp_server: "192.168.178.4"
  tasks:
    - name: Variablen anzeigen
      debug:
        msg: "Host: {{ ansible_host }} User: {{ ansible_user }}"

    - name: Timeserver konfigurieren
      ansible.builtin.script:
        executable: python3
        cmd: /dev/stdin
        stdin: |
          import requests
          from requests.auth import HTTPDigestAuth
          import json
          r = requests.post(
              'http://{{ ansible_host }}/rpc',
              json={'id':1,'method':'Sys.SetConfig','params':{'config':{'sntp':{'server':'{{ ntp_server }}'}}}},
              auth=HTTPDigestAuth('{{ ansible_user }}', '{{ ansible_password }}'),
              timeout=10
          )
          print(r.text)
      register: result

    - name: Ergebnis anzeigen
      debug:
        msg: "Ergebnis: {{ result.stdout }}"
