---
- name: Shelly Gen2/3 - Timeserver setzen
  hosts: shelly_gen2
  gather_facts: false
  tasks:
    - name: Variablen anzeigen
      debug:
        msg: "Host: {{ ansible_host }} User: {{ ansible_user }}"

    - name: Timeserver konfigurieren
      ansible.builtin.script:
        cmd: "files/shelly_gen2_sntp.py {{ ansible_host }} {{ ansible_user }} {{ ansible_password }} {{ ntp_server }}"
        executable: python3
      register: result
      changed_when: "'\"changed\": true' in result.stdout"
      notify: Shelly neu starten

    - name: Ergebnis anzeigen
      debug:
        msg: "Ergebnis: {{ result.stdout }}"

  handlers:
    - name: Shelly neu starten
      ansible.builtin.script:
        cmd: "files/shelly_gen2_reboot.py {{ ansible_host }} {{ ansible_user }} {{ ansible_password }}"
        executable: python3
